### ISSUE TITLE
[RangeError: Maximum call stack size exceeded] for big JSON data

### ISSUE THREAD

**Issue by tim-kos** [ckknight/async-json#2]
Hey there,

thank you for a nice module.

I am running into a Maximum call stack size exceeded error when stringifying a big JSON object. Also, my provided callback will be fired multiple times then.

To reproduce, download http://static.transloadit.com/giant.json, then JSON.parse() its contents and try to stringify it using the module. It will throw that error.

Without this issue fixed, I cannot use the module even though I'd love to. : /

Kind regards,
Tim

**Comment by tim-kos** [comment]
I think the problem is that the handle() functions here https://github.com/ckknight/async-json/blob/master/lib/async-json.js#L80 and here https://github.com/ckknight/async-json/blob/master/lib/async-json.js#L142 have recursive calls. I think a setTimeout(function() {}, 0); should help node clear the stack and fix the problem. I will try that. If it works, I will submit a PR.

**Comment by tim-kos** [comment]
There you go fine Sir!

**Comment by tim-kos** [comment]
Could you please update the npm version so that we can benefit from the other solution easily?

**Comment by kvz** [comment]
:heart_eyes:

**Comment by ckknight** [comment]
Whoops, forgot about that, @tim-kos. Will do.
